channels:                    # Lists package sources to install from
- defaults                   # Default Anaconda Repository
- conda-forge

dependencies:
# Building
- cmake >= 3.17
- ninja >= 1.9

# C++ libraries
- highfive # HDF5
- eigen # Matrix and vectors
- libgomp # for OpenMP
- openmp # parallelize eigen
- ann # Approximate nearest neighbors

# Python and libraries
- python >= 3.7
- pip
- h5py
- pybind11 >= 2.5

# Notebooks and ipython
- ipython
- ipykernel
- notebook
